# Generated by Django 5.0.7 on 2025-08-01 05:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Project title or name', max_length=255)),
                ('description', models.TextField(help_text='Detailed project description')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='planning', help_text='Current status of the project', max_length=20)),
                ('cost', models.DecimalField(decimal_places=2, help_text='Total project cost', max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='Discount amount (if any)', max_digits=12)),
                ('start_date', models.DateField(blank=True, help_text='Project start date', null=True)),
                ('deadline', models.DateField(blank=True, help_text='Project deadline', null=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Whether the project has been verified')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='Client who owns this project', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='clients.client')),
                ('created_by', models.ForeignKey(help_text='Salesperson who created this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to='organization.salesperson')),
                ('manager', models.ForeignKey(blank=True, help_text='Project manager assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to='organization.projectmanager')),
                ('verifier', models.ForeignKey(blank=True, help_text='Verifier assigned to this project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_projects', to='organization.verifier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='projects_pr_status_f023cb_idx'), models.Index(fields=['created_at'], name='projects_pr_created_6b02e3_idx'), models.Index(fields=['is_verified'], name='projects_pr_is_veri_48b6e6_idx')],
            },
        ),
    ]
