# Generated by Django 5.0.7 on 2025-08-02 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('superadmin', 'Superadmin')], default='user', max_length=32),
        ),
    ]
