# Generated by Django 5.0.7 on 2025-08-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='welcome_email_sent',
            field=models.BooleanField(default=False, help_text='Whether the welcome email has been sent to this user.'),
        ),
    ]
