# Generated by Django 5.0.7 on 2025-08-02 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_welcome_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='welcome_email_sent',
        ),
    ]
