# Generated by Django 5.0.7 on 2025-08-07 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Short description of the task', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed task description', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('blocked', 'Blocked')], default='pending', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Task priority level', max_length=10)),
                ('due_date', models.DateTimeField(blank=True, help_text='When this task is due', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('developer', models.ForeignKey(blank=True, help_text='Developer assigned to this task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organization.organizationmember')),
                ('project', models.ForeignKey(help_text='Project this task belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='projects.project')),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='tasks_task_status_4a0a95_idx'), models.Index(fields=['priority'], name='tasks_task_priorit_a900d4_idx'), models.Index(fields=['due_date'], name='tasks_task_due_dat_bce847_idx')],
            },
        ),
    ]
