# Generated by Django 5.0.7 on 2025-08-07 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='organization.organization'),
        ),
        migrations.AddField(
            model_name='client',
            name='salesperson',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'salesperson'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='organization.organizationmember'),
        ),
    ]
