# Generated by Django 5.0.7 on 2025-08-08 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='max_storage',
            field=models.PositiveIntegerField(default=10, help_text='Maximum storage in GB allowed for this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='max_users',
            field=models.PositiveIntegerField(default=10, help_text='Maximum number of users allowed for this organization'),
        ),
        migrations.AddField(
            model_name='organization',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trial', 'Trial'), ('suspended', 'Suspended'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
    ]
