# Generated by Django 5.0.7 on 2025-08-09 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_add_organization_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanDuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration_months', models.PositiveIntegerField(help_text='Duration in months (e.g., 1, 3, 6, 12)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default duration shown for the plan')),
            ],
            options={
                'ordering': ['duration_months'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='organization',
            name='plan',
        ),
        migrations.AddField(
            model_name='organization',
            name='legacy_plan',
            field=models.CharField(blank=True, help_text='Legacy plan field for migration. Use subscription relation instead.', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='organization.organization')),
                ('plan_duration', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='organization.planduration')),
            ],
        ),
        migrations.AddField(
            model_name='planduration',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='durations', to='organization.subscriptionplan'),
        ),
        migrations.AlterUniqueTogether(
            name='planduration',
            unique_together={('plan', 'duration_months')},
        ),
    ]
