# Generated by Django 5.0.7 on 2025-08-02 11:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_migrate_roles_to_organization_member'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='developers', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='developer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='developer_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organizationmember',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('salesperson', 'Salesperson'), ('verifier', 'Verifier'), ('project_manager', 'Project Manager'), ('developer', 'Developer'), ('support', 'Support')], default='developer', max_length=32),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_managers', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='projectmanager',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_manager_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salespersons', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='salesperson',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='salesperson_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='support',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_staff', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='support',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='support_role', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verifier',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifiers', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='verifier',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verifier_role', to=settings.AUTH_USER_MODEL),
        ),
    ]
