# Generated by Django 5.0.7 on 2025-08-09 04:07

from django.db import migrations


def create_initial_plans(apps, schema_editor):
    """Create initial subscription plans and durations."""
    SubscriptionPlan = apps.get_model('organization', 'SubscriptionPlan')
    PlanDuration = apps.get_model('organization', 'PlanDuration')
    
    # Create Basic Plan
    basic = SubscriptionPlan.objects.create(
        name='Basic',
        description='Basic plan with essential features',
        is_active=True
    )
    
    # Create Pro Plan
    pro = SubscriptionPlan.objects.create(
        name='Pro',
        description='Professional plan with advanced features',
        is_active=True
    )
    
    # Create Enterprise Plan
    enterprise = SubscriptionPlan.objects.create(
        name='Enterprise',
        description='Enterprise plan with premium features and support',
        is_active=True
    )
    
    # Create default durations for each plan
    plans = [basic, pro, enterprise]
    durations = [
        # (months, price, discount_percentage, is_default)
        (1, 29.99, 0, True),    # 1 month - no discount
        (3, 85.47, 5, False),   # 3 months - 5% discount
        (6, 161.97, 10, False),  # 6 months - 10% discount
        (12, 305.94, 15, False)  # 12 months - 15% discount
    ]
    
    for plan in plans:
        base_price = 29.99 if plan.name == 'Basic' else (99.99 if plan.name == 'Pro' else 299.99)
        for months, price, discount, is_default in durations:
            PlanDuration.objects.create(
                plan=plan,
                duration_months=months,
                price=round(price * (299.99/29.99) if plan.name == 'Enterprise' else (price * (99.99/29.99) if plan.name == 'Pro' else price), 2),
                discount_percentage=discount,
                is_default=is_default,
                is_active=True
            )


def delete_initial_plans(apps, schema_editor):
    """Delete all subscription plans and their durations."""
    SubscriptionPlan = apps.get_model('organization', 'SubscriptionPlan')
    PlanDuration = apps.get_model('organization', 'PlanDuration')
    
    # Delete all durations first to avoid foreign key constraint
    PlanDuration.objects.all().delete()
    # Then delete all plans
    SubscriptionPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_planduration_subscriptionplan_and_more'),
    ]

    operations = [
        migrations.RunPython(create_initial_plans, delete_initial_plans),
    ]
