# Generated by Django 5.0.7 on 2025-08-09 06:38

from django.db import migrations


def create_plans(apps, schema_editor):
    """Create subscription plans and their durations."""
    SubscriptionPlan = apps.get_model('organization', 'SubscriptionPlan')
    PlanDuration = apps.get_model('organization', 'PlanDuration')
    
    # Create subscription plans
    monthly = SubscriptionPlan.objects.create(
        name="Monthly",
        description="Flexible monthly subscription with full features",
        is_active=True
    )

    quarterly = SubscriptionPlan.objects.create(
        name="Quarterly",
        description="3-month subscription with 10% savings",
        is_active=True
    )

    annual = SubscriptionPlan.objects.create(
        name="Annual",
        description="12-month subscription with 25% savings",
        is_active=True
    )

    # Create durations for each plan
    # Monthly plan (1 month at regular price)
    PlanDuration.objects.create(
        plan=monthly,
        duration_months=1,
        price=99.00,
        discount_percentage=0,
        is_default=True
    )

    # Quarterly plan (3 months with 10% discount)
    PlanDuration.objects.create(
        plan=quarterly,
        duration_months=3,
        price=267.30,  # 3 months with 10% discount
        discount_percentage=10,
        is_default=True
    )

    # Annual plan (12 months with 25% discount)
    PlanDuration.objects.create(
        plan=annual,
        duration_months=12,
        price=891.00,  # 12 months with 25% discount
        discount_percentage=25,
        is_default=True
    )


def delete_plans(apps, schema_editor):
    """Delete all subscription plans and their durations."""
    SubscriptionPlan = apps.get_model('organization', 'SubscriptionPlan')
    PlanDuration = apps.get_model('organization', 'PlanDuration')
    
    # Delete all durations first to avoid foreign key constraint issues
    PlanDuration.objects.all().delete()
    # Then delete all plans
    SubscriptionPlan.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_populate_initial_subscription_plans'),
    ]

    operations = [
        migrations.RunPython(create_plans, delete_plans),
    ]
