# Generated by Django 5.0.7 on 2025-08-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_developer_organization_alter_developer_user_and_more'),
    ]

    operations = [
    ]
