# Generated by Django 5.0.7 on 2025-08-10 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_add_subscription_plans'),
    ]

    operations = [
    ]
