# Generated by Django 5.0.7 on 2025-08-07 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('organization', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR, GBP)', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the payment', max_length=20)),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('paypal', 'PayPal'), ('other', 'Other')], default='credit_card', help_text='Payment method used', max_length=20)),
                ('transaction_id', models.CharField(blank=True, help_text='Transaction ID from payment gateway', max_length=100, null=True)),
                ('verified', models.BooleanField(default=False, help_text='Whether the payment has been verified')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the payment', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='Client who made the payment', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client')),
                ('project', models.OneToOneField(blank=True, help_text='Project this payment is for', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='projects.project')),
                ('verified_by', models.ForeignKey(blank=True, help_text='Staff who verified this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_payments', to='organization.organizationmember')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_7ad4af_idx'), models.Index(fields=['created_at'], name='payments_pa_created_b8a300_idx'), models.Index(fields=['verified'], name='payments_pa_verifie_9ac3b6_idx')],
            },
        ),
    ]
