# Generated by Django 5.0.7 on 2025-08-07 19:09

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('organization', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('issue', models.CharField(blank=True, default='No issue description provided', help_text='Brief description of the issue', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the issue')),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', help_text='Current status of the ticket', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', help_text='Priority level of the ticket', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(help_text='Client who raised the ticket', on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='clients.client')),
                ('project', models.ForeignKey(blank=True, help_text='Related project (if applicable)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='projects.project')),
                ('support', models.ForeignKey(blank=True, help_text='Support staff assigned to this ticket', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_tickets', to='organization.organizationmember')),
            ],
            options={
                'ordering': ['-priority', 'created_at'],
                'indexes': [models.Index(fields=['status'], name='support_sup_status_c35d7c_idx'), models.Index(fields=['priority'], name='support_sup_priorit_049754_idx'), models.Index(fields=['created_at'], name='support_sup_created_83a137_idx')],
            },
        ),
    ]
